In [1]:
import numpy as np

In [2]:
# Generate random numbers
rng = np.random.default_rng()

In [3]:
# Uniform inclusive of 0 and exclusive of 10
rng.integers(0,10,3)

array([5, 0, 8])

In [6]:
# Uniform inclusive of 0 and  10
rng.integers(0,10,3, endpoint=True)

array([ 9,  3, 10])

In [4]:
# Uniform, x belongs [0,1)
rng.random(3)

array([0.72175294, 0.0886603 , 0.80159783])

In [5]:
# Uniform inclusive of 0 and exclusive of 10
rng.uniform(1,10,3)

array([5.44827948, 4.7933101 , 2.88206522])

In [7]:
# Mean 0 and std deviation 1
rng.standard_normal(3)

array([ 0.5878078 ,  0.67988484, -0.83850319])

In [8]:
# Mean 5 and std. dev 3
rng.normal(5,2,3)

array([5.54222614, 7.24807366, 5.68900357])

In [10]:
a = np.array([1,2,3,4,5,6,7,6,5,4,3,2,1])

In [11]:
np.where(a > 5)

(array([5, 6, 7]),)

In [12]:
np.nonzero(a>5)

(array([5, 6, 7]),)

In [13]:
np.where(a >= 5,1,0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [14]:
np.clip(a,2,5)

array([2, 2, 3, 4, 5, 5, 5, 5, 5, 4, 3, 2, 2])

In [15]:
b = np.array([1,2,3,4,5])

In [16]:
b[::-1]

array([5, 4, 3, 2, 1])